[theme]
primaryColor = "#4CAF50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#000000"

[general]
email = "sumitkumar969074@gmail.com"

[server]
headless = true
port = 8501
enableCORS = false